[package]
name = "modland_hash"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]
edition = "2018"
Build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
walkdir = "2"
cc = { version = "1.0", features = ["parallel"] }

[dependencies]
walkdir = "2"
rayon = "1.1"
sha2 = "0.9.2"
